from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar
from copy import deepcopy


DEFAULT_THEME: dict[str, object] = {
    "body_background": "#f1f5f9",
    "surface_color": "#ffffff",
    "muted_surface_color": "#f4f7fb",
    "alt_surface_color": "#e8eef8",
    "text_color": "#213041",
    "heading_color": "#102033",
    "muted_text_color": "#617287",
    "primary_color": "#1d4ed8",
    "primary_text_color": "#ffffff",
    "secondary_color": "#dbe7ff",
    "secondary_text_color": "#1e3a8a",
    "accent_color": "#d97706",
    "border_color": "#d5deeb",
    "shadow_color": "rgba(15, 23, 42, 0.08)",
    "success_color": "#166534",
    "warning_color": "#b45309",
    "danger_color": "#b91c1c",
    "link_color": "#1d4ed8",
    "font_family": "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif",
    "heading_font_family": "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif",
    "base_font_size": "16px",
    "line_height": "1.5",
    "container_width": "600px",
    "content_padding": "24px",
    "content_padding_compact": "18px",
    "section_padding": "24px",
    "card_padding": "20px",
    "hero_padding": "24px",
    "section_gap": "18px",
    "gap_xs": "8px",
    "gap_sm": "12px",
    "gap_md": "16px",
    "gap_lg": "24px",
    "gap_xl": "32px",
    "radius_sm": "8px",
    "radius_md": "14px",
    "radius_lg": "20px",
    "radius_pill": "999px",
    "radius_card": "14px",
    "radius_panel": "20px",
    "button_padding": "12px 20px",
    "button_radius": "8px",
    "button_secondary_background": "#e8eefc",
    "button_secondary_text_color": "#1e3a8a",
    "button_ghost_text_color": "#1d4ed8",
    "pill_background": "#e8eefc",
    "pill_text_color": "#264167",
    "pill_success_background": "#dcfce7",
    "pill_success_text_color": "#166534",
    "pill_warning_background": "#fef3c7",
    "pill_warning_text_color": "#b45309",
    "pill_danger_background": "#fee2e2",
    "pill_danger_text_color": "#b91c1c",
    "eyebrow_background": "#dbe7ff",
    "eyebrow_text_color": "#1e40af",
    "hero_background": "#ffffff",
    "hero_accent_background": "#f4f7fb",
    "hero_border_color": "#dbe7ff",
    "card_background": "#ffffff",
    "card_featured_background": "#f8fbff",
    "card_border_color": "#d5deeb",
    "card_featured_border_color": "#93c5fd",
    "card_shadow": "0 10px 24px rgba(15, 23, 42, 0.08)",
    "surface_default_background": "#ffffff",
    "surface_default_border_color": "#d5deeb",
    "surface_default_shadow": "0 10px 24px rgba(15, 23, 42, 0.08)",
    "surface_subtle_background": "#f4f7fb",
    "surface_subtle_border_color": "#d5deeb",
    "surface_subtle_shadow": "none",
    "surface_featured_background": "#f8fbff",
    "surface_featured_border_color": "#93c5fd",
    "surface_featured_shadow": "0 10px 24px rgba(15, 23, 42, 0.08)",
    "surface_inverse_background": "#102033",
    "surface_inverse_border_color": "#102033",
    "surface_inverse_shadow": "none",
    "background_overlay_color": "rgba(16, 32, 51, 0.54)",
    "background_overlay_opacity": "0.54",
    "background_overlay_text_color": "#ffffff",
    "background_overlay_link_color": "#ffffff",
    "icon_tile_background": "#edf3fb",
    "icon_tile_border_color": "#d5deeb",
    "icon_tile_color": "#213041",
    "menu_link_color": "#4d5f75",
    "social_tile_background": "#edf3fb",
    "social_tile_border_color": "#d5deeb",
    "social_icon_color": "#213041",
    "metric_label_color": "#617287",
    "metric_detail_color": "#617287",
    "metric_trend_positive_background": "#dcfce7",
    "metric_trend_positive_color": "#166534",
    "metric_trend_negative_background": "#fee2e2",
    "metric_trend_negative_color": "#b91c1c",
    "image_grid_gap": "16px",
    "hero_title_size": "36px",
    "heading_size": "30px",
    "subheading_size": "22px",
    "title_small_size": "18px",
    "kicker_size": "12px",
    "body_small_size": "14px",
    "metric_value_size": "30px",
    "alert_info_background": "#e8f0ff",
    "alert_success_background": "#dcfce7",
    "alert_warning_background": "#fef3c7",
    "alert_danger_background": "#fee2e2",
    "divider_color": "#d8e2ef",
    "table_header_border_color": "#c5d4ea",
    "table_row_border_color": "#dde6f1",
    "table_header_padding": "12px 14px",
    "table_cell_padding": "12px 14px",
    "table_radius": "18px",
    "image_radius": "10px",
    "image_frame_background": "#edf3fb",
    "nav_link_color": "#4d5f75",
    "footer_text_color": "#5f7085",
}

THEMES: dict[str, dict[str, object]] = {
    "default": DEFAULT_THEME,
    "editorial": {
        **DEFAULT_THEME,
        "body_background": "#f6f0e8",
        "surface_color": "#fffdfa",
        "muted_surface_color": "#f2ebe1",
        "alt_surface_color": "#efe4d8",
        "text_color": "#43362b",
        "heading_color": "#2d241d",
        "muted_text_color": "#7a6858",
        "primary_color": "#7c3f1d",
        "secondary_color": "#efe2d3",
        "secondary_text_color": "#7c3f1d",
        "accent_color": "#bf6a2a",
        "link_color": "#7c3f1d",
        "nav_link_color": "#7a6858",
        "footer_text_color": "#7a6858",
        "font_family": "Arial, Helvetica, sans-serif",
        "heading_font_family": 'Georgia, "Times New Roman", serif',
        "content_padding": "30px",
        "section_gap": "22px",
        "radius_md": "10px",
        "radius_lg": "16px",
        "radius_card": "10px",
        "radius_panel": "16px",
        "button_radius": "12px",
        "button_secondary_background": "#f1e7db",
        "button_secondary_text_color": "#7c3f1d",
        "pill_background": "#efe2d3",
        "pill_text_color": "#7c3f1d",
        "eyebrow_background": "#efe2d3",
        "eyebrow_text_color": "#7c3f1d",
        "hero_accent_background": "#f7f1ea",
        "hero_border_color": "#e2d2c0",
        "card_featured_background": "#fbf6ef",
        "card_featured_border_color": "#d9b38c",
        "alert_info_background": "#f2ebe1",
        "divider_color": "#ddcfbf",
        "table_header_border_color": "#d3c0ad",
        "table_row_border_color": "#e6dbcf",
        "image_radius": "10px",
        "card_shadow": "0 10px 24px rgba(124, 63, 29, 0.08)",
        "hero_title_size": "40px",
        "heading_size": "32px",
    },
    "vibrant": {
        **DEFAULT_THEME,
        "body_background": "#fff4e8",
        "surface_color": "#fffaf4",
        "muted_surface_color": "#ffe7d1",
        "alt_surface_color": "#ffd7b3",
        "text_color": "#3b1f13",
        "heading_color": "#2a160f",
        "muted_text_color": "#815844",
        "primary_color": "#c2410c",
        "secondary_color": "#ffedd5",
        "secondary_text_color": "#9a3412",
        "accent_color": "#ea580c",
        "link_color": "#9a3412",
        "nav_link_color": "#9a3412",
        "footer_text_color": "#815844",
        "font_family": '"Trebuchet MS", Arial, Helvetica, sans-serif',
        "heading_font_family": '"Trebuchet MS", Arial, Helvetica, sans-serif',
        "content_padding": "26px",
        "radius_md": "18px",
        "radius_lg": "26px",
        "radius_card": "18px",
        "radius_panel": "26px",
        "button_radius": "18px",
        "button_secondary_background": "#ffe1c2",
        "button_secondary_text_color": "#9a3412",
        "pill_background": "#ffd8b5",
        "pill_text_color": "#9a3412",
        "eyebrow_background": "#ffedd5",
        "eyebrow_text_color": "#c2410c",
        "hero_background": "#fffaf4",
        "hero_accent_background": "#fff0df",
        "hero_border_color": "#f3caa4",
        "card_featured_background": "#fff2e4",
        "card_featured_border_color": "#fb923c",
        "alert_info_background": "#ffe7d1",
        "divider_color": "#f2c7a1",
        "table_header_border_color": "#f0b98a",
        "table_row_border_color": "#f7d9bd",
        "image_radius": "18px",
        "card_shadow": "0 16px 36px rgba(194, 65, 12, 0.12)",
    },
    "modern": {
        **DEFAULT_THEME,
        "body_background": "#eef2ff",
        "surface_color": "#ffffff",
        "primary_color": "#1d4ed8",
        "accent_color": "#0ea5e9",
        "link_color": "#1d4ed8",
        "radius_md": "16px",
        "radius_lg": "24px",
        "radius_card": "16px",
        "radius_panel": "24px",
        "button_radius": "999px",
        "eyebrow_background": "#dbeafe",
        "eyebrow_text_color": "#1d4ed8",
    },
    "commerce": {
        **DEFAULT_THEME,
        "body_background": "#fffbeb",
        "surface_color": "#ffffff",
        "primary_color": "#9a3412",
        "accent_color": "#ea580c",
        "link_color": "#9a3412",
        "nav_link_color": "#9a3412",
        "muted_surface_color": "#fff7ed",
        "alt_surface_color": "#ffedd5",
        "eyebrow_background": "#ffedd5",
        "eyebrow_text_color": "#9a3412",
        "secondary_color": "#ffedd5",
        "secondary_text_color": "#9a3412",
        "hero_accent_background": "#fff6ea",
        "hero_border_color": "#fed7aa",
        "card_featured_background": "#fff7ed",
        "card_featured_border_color": "#fb923c",
        "card_shadow": "0 14px 30px rgba(154, 52, 18, 0.08)",
    },
}

_CURRENT_THEME: ContextVar[dict[str, object] | None] = ContextVar("_CURRENT_THEME", default=None)


@contextmanager
def use_theme(theme: dict[str, object]):
    token = _CURRENT_THEME.set(deepcopy(theme))
    try:
        yield
    finally:
        _CURRENT_THEME.reset(token)


def build_theme(base: str | dict[str, object] | None = None, overrides: dict[str, object] | None = None) -> dict[str, object]:
    if isinstance(base, str):
        theme = deepcopy(THEMES.get(base, DEFAULT_THEME))
    elif isinstance(base, dict):
        theme = deepcopy({**DEFAULT_THEME, **base})
    else:
        inherited = _CURRENT_THEME.get()
        theme = deepcopy(inherited if inherited is not None else DEFAULT_THEME)
    if overrides:
        theme.update(overrides)
    return theme
